### ISSUE TITLE
Potential optimizations

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#269]
Some ideas about optimizations we could implement:

```[tasklist]
### Tasks
- [x] https://github.com/candy-lang/candy/issues/270
- [ ] Compiler: Function inlining
- [x] Compiler: Detect pure functions and deduplicate calls
- [ ] MIR: Use FxHashSet in `expression.captured_ids()` and `body.all_ids()`
- [ ] MIR: Remove responsible parameter if function can't panic
- [ ] https://github.com/candy-lang/candy/issues/291
- [x] ~VM: Try deduplicating heap objects in `BuiltinFunction::Equals`~ Can break assumptions about ref-counting
- [ ] Create unchecked mode with fewer asserts, etc.
- [ ] https://github.com/candy-lang/candy/pull/589
- [ ] https://github.com/candy-lang/candy/pull/583
- [ ] https://github.com/candy-lang/candy/pull/590
- [x] MIR: Deduplicate symbols
- [ ] LIR: Remove drops after panic
- [x] MIR: Remove code after panic
- [x] MIR: Tracing mode to avoid call tracing if call can never panic
- [ ] Inline iterators / recursive calls in generat
- [ ] Remove unnecessary return type checks
- [ ] VM: Inline objects for empty list and struct
- [ ] Compile matches to nested if/elses to aid constant folding
- [ ] InlineObject for non-capturing functions
- [ ] Convert captures to parameters where possible
```
