### ISSUE TITLE
Create packages

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#304]
Create packages:

```[tasklist]
### Packages
- [ ] stdin/out utilities like a print function
- [ ] https://github.com/candy-lang/candy/issues/905
- [ ] logging
- [ ] https://github.com/candy-lang/candy/issues/787
- [ ] Markdown
- [ ] custom binary serialization
- [ ] Cap'n Proto
- [ ] https://github.com/candy-lang/candy/issues/732
- [ ] SI?
- [ ] MongoDB?
- [ ] https://github.com/candy-lang/candy/issues/883
- [ ] https://github.com/candy-lang/candy/issues/984
- [ ] https://github.com/candy-lang/candy/issues/935
- [ ] https://github.com/candy-lang/candy/issues/938
- [ ] https://github.com/candy-lang/candy/issues/968
```
