### ISSUE TITLE
Expand IDE support

### ISSUE THREAD

**Issue by MarcelGarus** [candy-lang/candy#308]
```[tasklist]
### Lifecycle Messages
- [x] Initialize
- [x] Initialized
- [ ] Register Capability
- [ ] Unregister Capability
- [ ] Set Trace
- [ ] Log Trace
- [x] Shutdown
- [ ] Exit
```

```[tasklist]
### Document Synchronization
- [x] Did Open Text Document
- [x] Did Change Text Document
- [ ] Will Save Text Document
- [ ] Will Save Document Wait Until
- [ ] Did Save Text Document
- [x] Did Close Text Document
- [ ] Rename a Text Document
- [ ] Overview - Notebook Document
- [ ] Did Open Notebook Document
- [ ] Did Change Notebook Document
- [ ] Did Save Notebook Document
- [ ] Did Close Notebook Document
```

```[tasklist]
### Language Features
- [ ] ~Go to Declaration~
- [x] Go to Definition
- [ ] ~Go to Type Definition~
- [ ] ~Go to Implementation~
- [x] Find References: #155
- [ ] Prepare Call Hierarchy
- [ ] Call Hierarchy Incoming Calls
- [ ] Call Hierarchy Outgoing Calls
- [ ] ~Prepare Type Hierarchy~
- [ ] ~Type Hierarchy Super Types~
- [ ] ~Type Hierarchy Sub Types~
- [x] Document Highlight: #155
- [ ] Document Link
- [ ] Document Link Resolve
- [ ] Hover
- [ ] Code Lens
- [ ] Code Lens Refresh
- [x] Folding Range
- [ ] Selection Range
- [ ] Document Symbols
- [x] Semantic Tokens
- [ ] ~Inline Value~
- [ ] ~Inline Value Refresh~
- [ ] ~Inlay Hint~
- [ ] ~Inlay Hint Resolve~
- [ ] ~Inlay Hint Refresh~
- [ ] Moniker
- [ ] Completion Proposals
- [ ] Completion Item Resolve
- [x] Publish Diagnostics
- [ ] Pull Diagnostics
- [ ] Signature Help
- [ ] Code Action
- [ ] Code Action Resolve
- [ ] Document Color
- [ ] Color Presentation
- [x] Formatting: #371
- [ ] Range Formatting
- [ ] On type Formatting
- [ ] Rename: #417
- [ ] Prepare Rename: #417
- [ ] Linked Editing Range
```

```[tasklist]
### Workspace Features
- [ ] Workspace Symbols
- [ ] Workspace Symbol Resolve
- [ ] Get Configuration
- [ ] Did Change Configuration
- [ ] Workspace Folders
- [ ] Did Change Workspace Folders
- [ ] Will Create Files
- [ ] Did Create Files
- [ ] Will Rename Files
- [ ] Did Rename Files
- [ ] Will Delete Files
- [ ] Did Delete Files
- [ ] Did Change Watched Files
- [ ] Execute Command
- [ ] Apply Edit
```
