### ISSUE TITLE
Code Action ideas

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#389]
```[tasklist]
### Tasks
- [ ] Order imports alphabetically
- [ ] Order struct keys in import destructuring alphabetically
- [ ] Remove unused identifier
- [ ] Extract common code
- [ ] Extract selected code into variable/function
- [ ] Constant evaluate and replace selected code
- [ ] Inline and maybe const-evaluate dependents of constant value (e.g., to remove feature flag)
```
