### ISSUE TITLE
Random package

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#730]
```[tasklist]
### Tasks
- [ ] Simplify API for creating an OS-seeded RNG and applying a distribution
- [ ] More (and good) RNGs
- [ ] More distributions
- [ ] `distributions.uniform.multipleFromList`
```

References:

- C++: https://en.cppreference.com/w/cpp/numeric/random
- F#: https://fsprojects.github.io/FsRandom/, https://fsprojects.github.io/FsRandom/documentation.html
- Haskell: https://hackage.haskell.org/package/random-1.2.1.1/docs/System-Random.html
- Rust RNGs: https://rust-random.github.io/book/guide-rngs.html
- Rust distributions: https://rust-random.github.io/book/guide-dist.html
- Rust non-uniform distributions: https://rust-random.github.io/rand/rand_distr/index.html
- PCGs: https://www.pcg-random.org/
