### ISSUE TITLE
HTTP Package

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#787]
```[tasklist]
### Common
- [ ] HTTP: IP Address, Port, Socket modules
```

```[tasklist]
### Server
- [ ] https://github.com/candy-lang/candy/issues/788
```

```[tasklist]
### Client
- [ ] HTTP: Basic Client
```
