### ISSUE TITLE
CSV Package

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#883]
```[tasklist]
### Tasks
- [ ] https://github.com/candy-lang/candy/issues/884
- [ ] https://github.com/candy-lang/candy/issues/888
- [ ] https://github.com/candy-lang/candy/issues/894
- [ ] CSV Config
```
