### ISSUE TITLE
FileSystem Package

### ISSUE THREAD

**Issue by JonasWanke** [candy-lang/candy#905]
```[tasklist]
### Tasks
- [ ] https://github.com/candy-lang/candy/issues/907
- [ ] https://github.com/candy-lang/candy/issues/910
- [ ] FileSystem Package: Write to file
- [ ] FileSystem Package: File metadata
- [ ] FileSystem Package: Directory access
```
